# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e41161ae3b4142e8ab00d1f8fcf1c51aa9832da8ed6a937f07ca348a93f7c96b5956c1feb0acf9d8d2f13072e73aea8d55dae5c4afe991c32d85099ce10241a

test:
  secret_key_base: d006023c3b729b068466809a08bc05593cb7a8ef9ddfb979bfde0c8c9829a2e0f29fb1138c1c537ff7267c3d754f07ff7789c3984669f39953a34290810f59cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
